# Generated by Django 5.1.1 on 2026-07-23 13:10

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='الاسم')),
                ('phone', models.CharField(max_length=15, verbose_name='الهاتف')),
                ('id_number', models.CharField(max_length=20, unique=True, verbose_name='رقم الهوية')),
                ('address', models.TextField(blank=True, verbose_name='العنوان')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='تاريخ الميلاد')),
                ('join_date', models.DateField(auto_now_add=True, verbose_name='تاريخ التسجيل')),
                ('subscription_start', models.DateField(verbose_name='بداية الاشتراك')),
                ('subscription_end', models.DateField(verbose_name='نهاية الاشتراك')),
                ('subscription_type', models.CharField(choices=[('monthly', 'شهري'), ('quarterly', 'ثلاثة أشهر'), ('yearly', 'سنوي')], default='monthly', max_length=50, verbose_name='نوع الاشتراك')),
                ('is_active', models.BooleanField(default=True, verbose_name='اشتراك فعال')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
            ],
            options={
                'verbose_name': 'عضو',
                'verbose_name_plural': 'الأعضاء',
                'ordering': ['-join_date'],
            },
        ),
        migrations.CreateModel(
            name='DailyAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in_date', models.DateField(default=datetime.date.today, verbose_name='تاريخ الدخول')),
                ('check_in_time', models.TimeField(auto_now_add=True, verbose_name='وقت الدخول')),
                ('notes', models.CharField(blank=True, max_length=100, verbose_name='ملاحظات')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance', to='members.member')),
            ],
            options={
                'verbose_name': 'دخول يومي',
                'verbose_name_plural': 'الدخول اليومي',
                'ordering': ['-check_in_date', '-check_in_time'],
                'unique_together': {('member', 'check_in_date')},
            },
        ),
    ]
