# Generated by Django 5.1.1 on 2026-07-23 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='frozen_days',
            field=models.IntegerField(default=0, verbose_name='عدد أيام التجميد'),
        ),
        migrations.AddField(
            model_name='member',
            name='frozen_end',
            field=models.DateField(blank=True, null=True, verbose_name='تاريخ انتهاء التجميد'),
        ),
        migrations.AddField(
            model_name='member',
            name='frozen_start',
            field=models.DateField(blank=True, null=True, verbose_name='تاريخ بدء التجميد'),
        ),
        migrations.AddField(
            model_name='member',
            name='is_frozen',
            field=models.BooleanField(default=False, verbose_name='اشتراك مجمد'),
        ),
        migrations.AddField(
            model_name='member',
            name='original_end',
            field=models.DateField(blank=True, null=True, verbose_name='تاريخ النهاية الأصلي'),
        ),
    ]
